# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgroll < Formula
  desc "Postgres zero-downtime migrations made easy"
  homepage "https://www.xata.io"
  version "0.16.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xataio/pgroll/releases/download/v0.16.2/pgroll.macos.amd64"
      sha256 "26cd2d297d02f377f9be2731647f63e66fe2d7df2bdf629a65f6d202a795996f"

      def install
        bin.install "pgroll.macos.amd64" => "pgroll"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xataio/pgroll/releases/download/v0.16.2/pgroll.macos.arm64"
      sha256 "2cf36178b9e4fb1880425d78b0aebbd076ef309c61148e12eb29cc80d82be036"

      def install
        bin.install "pgroll.macos.arm64" => "pgroll"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xataio/pgroll/releases/download/v0.16.2/pgroll.linux.amd64"
        sha256 "454ab2f6a9ddb36ad1d245121452bf26bf393065b38b4e0b1e155b67656cbd04"

        def install
          bin.install "pgroll.linux.amd64" => "pgroll"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xataio/pgroll/releases/download/v0.16.2/pgroll.linux.arm64"
        sha256 "08d00bf6ce267ade1e5e5b4f614de704e9c0d616f2e150aeeba50703a92a5262"

        def install
          bin.install "pgroll.linux.arm64" => "pgroll"
        end
      end
    end
  end
end
